import {
    ItemDefinition,
    ItemId,
} from './ItemTypes';

/**
 * ItemSystem / 道具系统
 *
 * 这里只定义“游戏里有哪些道具”。
 * 玩家实际拥有多少，由 InventorySystem 管理；
 * 持久化由 WarehouseSystem 管理；
 * 金币/钻石仍然属于 EconomySystem，不放进 ItemSystem。
 */
const ITEMS:
    Readonly<Record<ItemId, ItemDefinition>> = {
        monster_essence: {
            id: 'monster_essence',
            name: '魔物精华',
            category: 'material',
            rarity: 'common',
            stackLimit: 9999,
            description: '击败魔物后有概率获得的基础材料。',
            resourcePath: 'items/materials/monster_essence',
        },
        upgrade_stone: {
            id: 'upgrade_stone',
            name: '强化石',
            category: 'material',
            rarity: 'rare',
            stackLimit: 9999,
            description: '用于人物、装备或防御设施的强化。',
            resourcePath: 'items/materials/upgrade_stone',
        },
        tower_repair_stone: {
            id: 'tower_repair_stone',
            name: '雕像修复石',
            category: 'material',
            rarity: 'epic',
            stackLimit: 999,
            description: '用于守护雕像修复与高级培养。',
            resourcePath: 'items/materials/tower_repair_stone',
        },
        key: {
            id: 'key',
            name: '钥匙',
            category: 'special',
            rarity: 'rare',
            stackLimit: 999,
            description: '用于开启特定宝箱或玩法奖励。',
            resourcePath: 'items/special/key',
        },
        equipment_chest: {
            id: 'equipment_chest',
            name: '装备箱',
            category: 'special',
            rarity: 'rare',
            stackLimit: 999,
            description: '开启后获得装备类奖励。',
            resourcePath: 'items/special/equipment_chest',
        },
        summon_scroll: {
            id: 'summon_scroll',
            name: '召唤卷轴',
            category: 'special',
            rarity: 'epic',
            stackLimit: 999,
            description: '用于后续角色或伙伴召唤玩法。',
            resourcePath: 'items/special/summon_scroll',
        },
        weapon_sword: {
            id: 'weapon_sword',
            name: '武器·剑',
            category: 'equipment',
            rarity: 'common',
            stackLimit: 1,
            description: '近战武器示例。',
            resourcePath: 'items/equipment/weapon_sword',
        },
        shield: {
            id: 'shield',
            name: '盾牌',
            category: 'equipment',
            rarity: 'common',
            stackLimit: 1,
            description: '提升防御能力的装备。',
            resourcePath: 'items/equipment/shield',
        },
        armor: {
            id: 'armor',
            name: '盔甲',
            category: 'equipment',
            rarity: 'common',
            stackLimit: 1,
            description: '提升生存能力的装备。',
            resourcePath: 'items/equipment/armor',
        },
        boots: {
            id: 'boots',
            name: '靴子',
            category: 'equipment',
            rarity: 'common',
            stackLimit: 1,
            description: '提升移动或闪避相关属性的装备。',
            resourcePath: 'items/equipment/boots',
        },
        helmet: {
            id: 'helmet',
            name: '头盔',
            category: 'equipment',
            rarity: 'rare',
            stackLimit: 1,
            description: '防具槽位装备。',
            resourcePath: 'items/equipment/helmet',
        },
        ring: {
            id: 'ring',
            name: '戒指',
            category: 'equipment',
            rarity: 'rare',
            stackLimit: 1,
            description: '饰品槽位装备。',
            resourcePath: 'items/equipment/ring',
        },
        necklace: {
            id: 'necklace',
            name: '项链',
            category: 'equipment',
            rarity: 'rare',
            stackLimit: 1,
            description: '饰品槽位装备。',
            resourcePath: 'items/equipment/necklace',
        },
        wings: {
            id: 'wings',
            name: '翅膀',
            category: 'equipment',
            rarity: 'epic',
            stackLimit: 1,
            description: '后续高阶外观/属性装备。',
            resourcePath: 'items/equipment/wings',
        },
        hp_potion: {
            id: 'hp_potion',
            name: '生命药水',
            category: 'consumable',
            rarity: 'common',
            stackLimit: 99,
            description: '恢复生命值的消耗品。',
            resourcePath: 'items/consumables/hp_potion',
        },
        mp_potion: {
            id: 'mp_potion',
            name: '法力药水',
            category: 'consumable',
            rarity: 'common',
            stackLimit: 99,
            description: '预留的法力类消耗品。',
            resourcePath: 'items/consumables/mp_potion',
        },
        attack_potion: {
            id: 'attack_potion',
            name: '攻击药水',
            category: 'consumable',
            rarity: 'rare',
            stackLimit: 99,
            description: '临时提升攻击相关能力。',
            resourcePath: 'items/consumables/attack_potion',
        },
        defense_potion: {
            id: 'defense_potion',
            name: '防御药水',
            category: 'consumable',
            rarity: 'rare',
            stackLimit: 99,
            description: '临时提升防御相关能力。',
            resourcePath: 'items/consumables/defense_potion',
        },
        food: {
            id: 'food',
            name: '食物',
            category: 'consumable',
            rarity: 'common',
            stackLimit: 99,
            description: '体力与活动玩法可使用的食物类道具。',
            resourcePath: 'items/consumables/food',
        },
        exp_book: {
            id: 'exp_book',
            name: '经验书',
            category: 'consumable',
            rarity: 'rare',
            stackLimit: 999,
            description: '用于人物培养的经验类道具。',
            resourcePath: 'items/consumables/exp_book',
        },
        skill_book: {
            id: 'skill_book',
            name: '技能书',
            category: 'consumable',
            rarity: 'epic',
            stackLimit: 999,
            description: '用于技能培养或解锁。',
            resourcePath: 'items/consumables/skill_book',
        },
        advanced_material: {
            id: 'advanced_material',
            name: '进阶材料',
            category: 'material',
            rarity: 'epic',
            stackLimit: 9999,
            description: '用于角色或建筑进阶。',
            resourcePath: 'items/materials/advanced_material',
        },
        hero_shard: {
            id: 'hero_shard',
            name: '英雄碎片',
            category: 'material',
            rarity: 'epic',
            stackLimit: 9999,
            description: '人物收集与培养的碎片类材料。',
            resourcePath: 'items/materials/hero_shard',
        },
        artifact_fragment: {
            id: 'artifact_fragment',
            name: '神器碎片',
            category: 'material',
            rarity: 'legendary',
            stackLimit: 9999,
            description: '高阶长期成长材料。',
            resourcePath: 'items/materials/artifact_fragment',
        },
        wood: {
            id: 'wood',
            name: '木材',
            category: 'material',
            rarity: 'common',
            stackLimit: 9999,
            description: '领地和建筑玩法基础材料。',
            resourcePath: 'items/materials/wood',
        },
        stone: {
            id: 'stone',
            name: '石块',
            category: 'material',
            rarity: 'common',
            stackLimit: 9999,
            description: '领地和建筑玩法基础材料。',
            resourcePath: 'items/materials/stone',
        },
        iron: {
            id: 'iron',
            name: '铁锭',
            category: 'material',
            rarity: 'rare',
            stackLimit: 9999,
            description: '建筑和装备强化材料。',
            resourcePath: 'items/materials/iron',
        },
        magic_crystal: {
            id: 'magic_crystal',
            name: '魔能结晶',
            category: 'material',
            rarity: 'epic',
            stackLimit: 9999,
            description: '魔法类高阶材料。',
            resourcePath: 'items/materials/magic_crystal',
        },
        dragon_scale: {
            id: 'dragon_scale',
            name: '龙鳞',
            category: 'material',
            rarity: 'epic',
            stackLimit: 9999,
            description: 'Boss赤金炎龙相关稀有材料。',
            resourcePath: 'items/materials/dragon_scale',
        },
        magic_dust: {
            id: 'magic_dust',
            name: '魔法粉尘',
            category: 'material',
            rarity: 'rare',
            stackLimit: 9999,
            description: '法术与精英怪相关材料。',
            resourcePath: 'items/materials/magic_dust',
        },
    };

export class ItemCatalog {
    static get(id: ItemId): ItemDefinition {
        return ITEMS[id];
    }

    static getAll(): readonly ItemDefinition[] {
        return [
            ITEMS.monster_essence,
            ITEMS.upgrade_stone,
            ITEMS.tower_repair_stone,
            ITEMS.key,
            ITEMS.equipment_chest,
            ITEMS.summon_scroll,
            ITEMS.weapon_sword,
            ITEMS.shield,
            ITEMS.armor,
            ITEMS.boots,
            ITEMS.helmet,
            ITEMS.ring,
            ITEMS.necklace,
            ITEMS.wings,
            ITEMS.hp_potion,
            ITEMS.mp_potion,
            ITEMS.attack_potion,
            ITEMS.defense_potion,
            ITEMS.food,
            ITEMS.exp_book,
            ITEMS.skill_book,
            ITEMS.advanced_material,
            ITEMS.hero_shard,
            ITEMS.artifact_fragment,
            ITEMS.wood,
            ITEMS.stone,
            ITEMS.iron,
            ITEMS.magic_crystal,
            ITEMS.dragon_scale,
            ITEMS.magic_dust
        ];
    }

    static isItemId(value: string): value is ItemId {
        return value in ITEMS;
    }
}
